/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DriverDetailCreateNestedManyWithoutUsersInput } from "./DriverDetailCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ManifestCreateNestedManyWithoutUsersInput } from "./ManifestCreateNestedManyWithoutUsersInput";
import { TicketCreateNestedManyWithoutUsersInput } from "./TicketCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => DriverDetailCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DriverDetailCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DriverDetailCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  driverDetails?: DriverDetailCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ManifestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ManifestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ManifestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  manifests?: ManifestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  phoneNumber!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: () => TicketCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TicketCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TicketCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  tickets?: TicketCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
