/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ManifestService } from "../manifest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ManifestCreateInput } from "./ManifestCreateInput";
import { ManifestWhereInput } from "./ManifestWhereInput";
import { ManifestWhereUniqueInput } from "./ManifestWhereUniqueInput";
import { ManifestFindManyArgs } from "./ManifestFindManyArgs";
import { ManifestUpdateInput } from "./ManifestUpdateInput";
import { Manifest } from "./Manifest";
import { TicketFindManyArgs } from "../../ticket/base/TicketFindManyArgs";
import { Ticket } from "../../ticket/base/Ticket";
import { TicketWhereUniqueInput } from "../../ticket/base/TicketWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ManifestControllerBase {
  constructor(
    protected readonly service: ManifestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Manifest })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ManifestCreateInput): Promise<Manifest> {
    return await this.service.create({
      data: {
        ...data,

        driver: {
          connect: data.driver,
        },

        route: {
          connect: data.route,
        },

        vehicle: {
          connect: data.vehicle,
        },
      },
      select: {
        arrivalTime: true,
        createdAt: true,
        departureTime: true,

        driver: {
          select: {
            id: true,
          },
        },

        id: true,

        route: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Manifest] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ManifestFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Manifest[]> {
    const args = plainToClass(ManifestFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        arrivalTime: true,
        createdAt: true,
        departureTime: true,

        driver: {
          select: {
            id: true,
          },
        },

        id: true,

        route: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Manifest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ManifestWhereUniqueInput
  ): Promise<Manifest | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        arrivalTime: true,
        createdAt: true,
        departureTime: true,

        driver: {
          select: {
            id: true,
          },
        },

        id: true,

        route: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Manifest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ManifestWhereUniqueInput,
    @common.Body() data: ManifestUpdateInput
  ): Promise<Manifest | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          driver: {
            connect: data.driver,
          },

          route: {
            connect: data.route,
          },

          vehicle: {
            connect: data.vehicle,
          },
        },
        select: {
          arrivalTime: true,
          createdAt: true,
          departureTime: true,

          driver: {
            select: {
              id: true,
            },
          },

          id: true,

          route: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          vehicle: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Manifest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ManifestWhereUniqueInput
  ): Promise<Manifest | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          arrivalTime: true,
          createdAt: true,
          departureTime: true,

          driver: {
            select: {
              id: true,
            },
          },

          id: true,

          route: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          vehicle: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Ticket",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/ticket")
  @ApiNestedQuery(TicketFindManyArgs)
  async findManyTicket(
    @common.Req() request: Request,
    @common.Param() params: ManifestWhereUniqueInput
  ): Promise<Ticket[]> {
    const query = plainToClass(TicketFindManyArgs, request.query);
    const results = await this.service.findTicket(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        seatNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/ticket")
  async connectTicket(
    @common.Param() params: ManifestWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ticket: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/ticket")
  async updateTicket(
    @common.Param() params: ManifestWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ticket: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Manifest",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/ticket")
  async disconnectTicket(
    @common.Param() params: ManifestWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ticket: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
